# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EditPatient.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(719, 597)
        Dialog.setAutoFillBackground(True)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(460, 460, 161, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Save)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.BREEZETitle = QtGui.QLabel(Dialog)
        self.BREEZETitle.setGeometry(QtCore.QRect(130, 60, 471, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.BREEZETitle.setFont(font)
        self.BREEZETitle.setObjectName(_fromUtf8("BREEZETitle"))
        self.gridLayoutWidget_3 = QtGui.QWidget(Dialog)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(370, 160, 240, 251))
        self.gridLayoutWidget_3.setObjectName(_fromUtf8("gridLayoutWidget_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.WeightLabel = QtGui.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.WeightLabel.setFont(font)
        self.WeightLabel.setObjectName(_fromUtf8("WeightLabel"))
        self.gridLayout_3.addWidget(self.WeightLabel, 1, 0, 1, 1)
        self.WeightInput = QtGui.QDoubleSpinBox(self.gridLayoutWidget_3)
        self.WeightInput.setDecimals(1)
        self.WeightInput.setMaximum(300.0)
        self.WeightInput.setObjectName(_fromUtf8("WeightInput"))
        self.gridLayout_3.addWidget(self.WeightInput, 1, 1, 1, 1)
        self.GenderLabel = QtGui.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.GenderLabel.setFont(font)
        self.GenderLabel.setObjectName(_fromUtf8("GenderLabel"))
        self.gridLayout_3.addWidget(self.GenderLabel, 0, 0, 1, 1)
        self.EthnicGroupInput = QtGui.QComboBox(self.gridLayoutWidget_3)
        self.EthnicGroupInput.setObjectName(_fromUtf8("EthnicGroupInput"))
        self.EthnicGroupInput.addItem(_fromUtf8(""))
        self.EthnicGroupInput.addItem(_fromUtf8(""))
        self.EthnicGroupInput.addItem(_fromUtf8(""))
        self.EthnicGroupInput.addItem(_fromUtf8(""))
        self.EthnicGroupInput.addItem(_fromUtf8(""))
        self.EthnicGroupInput.addItem(_fromUtf8(""))
        self.EthnicGroupInput.addItem(_fromUtf8(""))
        self.EthnicGroupInput.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.EthnicGroupInput, 3, 1, 1, 1)
        self.HeightInput = QtGui.QDoubleSpinBox(self.gridLayoutWidget_3)
        self.HeightInput.setBaseSize(QtCore.QSize(0, 0))
        self.HeightInput.setAutoFillBackground(False)
        self.HeightInput.setDecimals(1)
        self.HeightInput.setMaximum(220.0)
        self.HeightInput.setObjectName(_fromUtf8("HeightInput"))
        self.gridLayout_3.addWidget(self.HeightInput, 2, 1, 1, 1)
        self.EthnicGroupLabel = QtGui.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.EthnicGroupLabel.setFont(font)
        self.EthnicGroupLabel.setObjectName(_fromUtf8("EthnicGroupLabel"))
        self.gridLayout_3.addWidget(self.EthnicGroupLabel, 3, 0, 1, 1)
        self.GenderInput = QtGui.QComboBox(self.gridLayoutWidget_3)
        self.GenderInput.setObjectName(_fromUtf8("GenderInput"))
        self.GenderInput.addItem(_fromUtf8(""))
        self.GenderInput.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.GenderInput, 0, 1, 1, 1)
        self.HeightLabel = QtGui.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.HeightLabel.setFont(font)
        self.HeightLabel.setObjectName(_fromUtf8("HeightLabel"))
        self.gridLayout_3.addWidget(self.HeightLabel, 2, 0, 1, 1)
        self.CurrentDiagnosisLabel = QtGui.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CurrentDiagnosisLabel.setFont(font)
        self.CurrentDiagnosisLabel.setObjectName(_fromUtf8("CurrentDiagnosisLabel"))
        self.gridLayout_3.addWidget(self.CurrentDiagnosisLabel, 4, 0, 1, 1)
        self.CurrentDiagnosisInput = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.CurrentDiagnosisInput.setObjectName(_fromUtf8("CurrentDiagnosisInput"))
        self.gridLayout_3.addWidget(self.CurrentDiagnosisInput, 4, 1, 1, 1)
        self.gridLayoutWidget_2 = QtGui.QWidget(Dialog)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(100, 160, 230, 201))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.LastNameLabel = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.LastNameLabel.setFont(font)
        self.LastNameLabel.setObjectName(_fromUtf8("LastNameLabel"))
        self.gridLayout_2.addWidget(self.LastNameLabel, 2, 0, 1, 1)
        self.LastNameInput = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.LastNameInput.setObjectName(_fromUtf8("LastNameInput"))
        self.gridLayout_2.addWidget(self.LastNameInput, 2, 1, 1, 1)
        self.PatientIDInput = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.PatientIDInput.setObjectName(_fromUtf8("PatientIDInput"))
        self.gridLayout_2.addWidget(self.PatientIDInput, 0, 1, 1, 1)
        self.FirstNameInput = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.FirstNameInput.setObjectName(_fromUtf8("FirstNameInput"))
        self.gridLayout_2.addWidget(self.FirstNameInput, 1, 1, 1, 1)
        self.DOBLabel = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.DOBLabel.setFont(font)
        self.DOBLabel.setObjectName(_fromUtf8("DOBLabel"))
        self.gridLayout_2.addWidget(self.DOBLabel, 3, 0, 1, 1)
        self.DOBInput = QtGui.QDateEdit(self.gridLayoutWidget_2)
        self.DOBInput.setMinimumDate(QtCore.QDate(1917, 9, 14))
        self.DOBInput.setObjectName(_fromUtf8("DOBInput"))
        self.gridLayout_2.addWidget(self.DOBInput, 3, 1, 1, 1)
        self.FirstNameLabel = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.FirstNameLabel.setFont(font)
        self.FirstNameLabel.setObjectName(_fromUtf8("FirstNameLabel"))
        self.gridLayout_2.addWidget(self.FirstNameLabel, 1, 0, 1, 1)
        self.PatientIDLabel = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.PatientIDLabel.setFont(font)
        self.PatientIDLabel.setObjectName(_fromUtf8("PatientIDLabel"))
        self.gridLayout_2.addWidget(self.PatientIDLabel, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.BREEZETitle.setText(_translate("Dialog", "PLEASE INPUT PATIENT DETAILS", None))
        self.WeightLabel.setText(_translate("Dialog", "Weight (kg)", None))
        self.GenderLabel.setText(_translate("Dialog", "Gender", None))
        self.EthnicGroupInput.setItemText(0, _translate("Dialog", "African", None))
        self.EthnicGroupInput.setItemText(1, _translate("Dialog", "Arabic", None))
        self.EthnicGroupInput.setItemText(2, _translate("Dialog", "European", None))
        self.EthnicGroupInput.setItemText(3, _translate("Dialog", "Indian", None))
        self.EthnicGroupInput.setItemText(4, _translate("Dialog", "Latino", None))
        self.EthnicGroupInput.setItemText(5, _translate("Dialog", "North Asian", None))
        self.EthnicGroupInput.setItemText(6, _translate("Dialog", "Western", None))
        self.EthnicGroupInput.setItemText(7, _translate("Dialog", "Other", None))
        self.EthnicGroupLabel.setText(_translate("Dialog", "Ethnic Group", None))
        self.GenderInput.setItemText(0, _translate("Dialog", "Male", None))
        self.GenderInput.setItemText(1, _translate("Dialog", "Female", None))
        self.HeightLabel.setText(_translate("Dialog", "Height (cm)", None))
        self.CurrentDiagnosisLabel.setText(_translate("Dialog", "Current Diagnosis", None))
        self.LastNameLabel.setText(_translate("Dialog", "Last Name", None))
        self.DOBLabel.setText(_translate("Dialog", "Date of Birth", None))
        self.DOBInput.setDisplayFormat(_translate("Dialog", "dd/MM/yyyy", None))
        self.FirstNameLabel.setText(_translate("Dialog", "First Name", None))
        self.PatientIDLabel.setText(_translate("Dialog", "Patient ID", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

